server:
  port: 8080

sfg.brewery.beer-inventory-service-host: http://localhost:8082


spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
  h2:
    console:
      enabled: true